# Generated by Django 4.2.28 on 2026-03-14 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OsintSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('query_type', models.CharField(choices=[('id', 'User ID'), ('username', 'Username'), ('text', 'Text Search')], max_length=20)),
                ('resolved_id', models.BigIntegerField(blank=True, null=True)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('api_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('searched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='OsintCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_type', models.CharField(choices=[('stats_min', 'Basic Stats (free)'), ('groups_count', 'Groups Count (free)'), ('messages_count', 'Messages Count (free)'), ('reputation', 'Reputation (free)'), ('stats_full', 'Full Stats (1)'), ('groups', 'Groups (5)'), ('names', 'Name History (3)'), ('usernames', 'Username History (3)'), ('stickers', 'Stickers (1)'), ('gifts', 'Gift Relations (5)'), ('common_groups_stat', 'Common Groups Stat (5)'), ('messages', 'Messages (10)'), ('basic_info', 'Basic Info (0.10)'), ('resolve_username', 'Resolve Username (0.10)'), ('username_usage', 'Username Usage (0.1)'), ('group_info', 'Group Info (0.01)'), ('group_members', 'Group Members (15)'), ('common_groups', 'Common Groups (0.5)'), ('text_search', 'Text Search (0.1)')], db_index=True, max_length=30)),
                ('target_id', models.CharField(db_index=True, help_text='Telegram user/group ID, username, or search query', max_length=255)),
                ('page', models.PositiveIntegerField(default=1, help_text='Page for paginated endpoints')),
                ('data', models.JSONField(help_text="The 'data' payload from FunStat response")),
                ('tech', models.JSONField(blank=True, default=dict, help_text="The 'tech' metadata (request_cost, current_ballance, duration)")),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OSINT Cache Entry',
                'verbose_name_plural': 'OSINT Cache Entries',
                'ordering': ['-fetched_at'],
                'unique_together': {('endpoint_type', 'target_id', 'page')},
            },
        ),
    ]
