# Generated by Django 4.2.28 on 2026-03-15 00:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('botproxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osintsearchlog',
            name='searched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
