# Generated by Django 4.2.28 on 2026-03-15 00:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('botproxy', '0002_alter_osintsearchlog_searched_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsintPhotoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(db_index=True, help_text='Telegram entity ID (user, group, channel, bot)', max_length=64, unique=True)),
                ('has_photo', models.BooleanField(default=False, help_text='Whether this entity has a profile photo')),
                ('photo_path', models.CharField(blank=True, default='', help_text='Relative path under MEDIA_ROOT', max_length=255)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_size', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'OSINT Photo Cache',
                'verbose_name_plural': 'OSINT Photo Cache',
            },
        ),
    ]
