# Generated by Django 4.2.28 on 2026-03-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botproxy', '0003_osintphotocache'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_string', models.TextField(help_text='Telethon StringSession.save() natijasi')),
                ('account_id', models.BigIntegerField(blank=True, help_text='Telegram account ID (me.id)', null=True)),
                ('account_name', models.CharField(blank=True, default='', help_text='Account display name (first_name + username)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Session',
                'verbose_name_plural': 'Telegram Sessions',
            },
        ),
    ]
