# Generated by Django 4.2.28 on 2026-03-15 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botproxy', '0004_telegramsession'),
        ('telegram', '0002_data_migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OsintPhotoCache',
        ),
        migrations.DeleteModel(
            name='TelegramSession',
        ),
    ]
