# Generated by Django 4.2.28 on 2026-03-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botproxy', '0005_delete_osintphotocache_delete_telegramsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osintcache',
            name='endpoint_type',
            field=models.CharField(choices=[('stats_min', 'Basic Stats (free)'), ('groups_count', 'Groups Count (free)'), ('messages_count', 'Messages Count (free)'), ('reputation', 'Reputation (free)'), ('stats_full', 'Full Stats (1)'), ('groups', 'Groups (5)'), ('names', 'Name History (3)'), ('usernames', 'Username History (3)'), ('stickers', 'Stickers (1)'), ('gifts', 'Gift Relations (5)'), ('common_groups_stat', 'Common Groups Stat (5)'), ('messages', 'Messages (10)'), ('basic_info', 'Basic Info (0.10)'), ('resolve_username', 'Resolve Username (0.10)'), ('username_usage', 'Username Usage (0.1)'), ('group_info', 'Group Info (0.01)'), ('group_members', 'Group Members (15)'), ('common_groups', 'Common Groups (0.5)'), ('text_search', 'Text Search (0.1)'), ('channel_profile', 'Channel Profile (Telethon)'), ('channel_messages', 'Channel Messages (Telethon)'), ('channel_search', 'Channel Search (Telethon)')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='osintsearchlog',
            name='query_type',
            field=models.CharField(choices=[('id', 'User ID'), ('username', 'Username'), ('text', 'Text Search'), ('channel', 'Channel/Group')], max_length=20),
        ),
    ]
