# Generated by Django 4.2.28 on 2026-03-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('botproxy', '0007_remove_osint_models_state_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotProxyPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_bot_dashboard', 'Can view bot dashboard and read-only data'), ('manage_polls', 'Can create, close, delete, publish polls'), ('manage_bot_admins', 'Can add/remove bot admins'), ('manage_universities', 'Can CRUD universities'), ('manage_telegram_session', 'Can manage Telegram MTProto session'), ('export_data', 'Can download CSV/PDF/JSON exports')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
