# Generated by Django 4.2.28 on 2026-02-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_rich',
            field=models.TextField(blank=True, help_text='Rich text content (HTML)', null=True),
        ),
    ]
