# Generated by Django 4.2.28 on 2026-03-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_content'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_published', '-created_at'], name='post_published_date'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug', 'is_published'], name='post_slug_published'),
        ),
    ]
