# Generated by Django 4.2.28 on 2026-04-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_post_published_date_post_post_slug_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_xo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_rich_en',
            field=models.TextField(blank=True, help_text='Rich text content (HTML)', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_rich_ru',
            field=models.TextField(blank=True, help_text='Rich text content (HTML)', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_rich_uz',
            field=models.TextField(blank=True, help_text='Rich text content (HTML)', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_rich_xo',
            field=models.TextField(blank=True, help_text='Rich text content (HTML)', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_ru',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_uz',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_xo',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_xo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_xo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
