# Generated by Django 4.2.28 on 2026-03-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['-created_at', 'is_read'], name='contact_date_read'),
        ),
    ]
