# Generated by Django 4.2.28 on 2026-04-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_unit', models.CharField(db_index=True, help_text='Systemd unit name, e.g. "uzexam-bot" or "postgresql@16-main".', max_length=80)),
                ('service_group', models.CharField(blank=True, db_index=True, help_text='apps / infra / mail / security', max_length=20)),
                ('service_display', models.CharField(blank=True, help_text='Human-readable name shown in alerts.', max_length=120)),
                ('is_active', models.BooleanField(db_index=True)),
                ('status_text', models.CharField(help_text='Raw `systemctl is-active` output: active / inactive / failed / activating.', max_length=40)),
                ('memory_mb', models.FloatField(blank=True, null=True)),
                ('uptime_text', models.CharField(blank=True, max_length=120)),
                ('is_state_change', models.BooleanField(db_index=True, default=False, help_text='True when this row differs from the previous check.')),
                ('previous_active', models.BooleanField(blank=True, help_text='Active state of the previous check, if any.', null=True)),
                ('alert_sent', models.BooleanField(db_index=True, default=False, help_text='Telegram alert was dispatched (only critical services).')),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Servis tekshiruvi',
                'verbose_name_plural': 'Servis tekshiruvlari',
                'ordering': ('-checked_at',),
                'indexes': [models.Index(fields=['service_unit', '-checked_at'], name='servermonit_service_89da2b_idx'), models.Index(fields=['is_state_change', '-checked_at'], name='servermonit_is_stat_e56300_idx'), models.Index(fields=['service_group', '-checked_at'], name='servermonit_service_139076_idx')],
            },
        ),
    ]
