# Generated by Django 4.2.28 on 2026-04-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedCron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(db_index=True, help_text='Django management command nomi.', max_length=120, unique=True)),
                ('verbose_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('schedule', models.CharField(blank=True, help_text='Cron format: "*/10 * * * *". Faqat axborot — server crontab source of truth.', max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cron jadval',
                'verbose_name_plural': 'Cron jadvallar',
                'ordering': ('category', 'command'),
            },
        ),
        migrations.CreateModel(
            name='CronRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(db_index=True, max_length=120)),
                ('args', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('running', 'Ishlamoqda'), ('success', 'Muvaffaqiyatli'), ('failed', 'Xatolik')], db_index=True, default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('error_summary', models.CharField(blank=True, max_length=300)),
                ('triggered_by', models.CharField(db_index=True, default='cron', max_length=20)),
                ('hostname', models.CharField(blank=True, max_length=80)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Cron yurishi',
                'verbose_name_plural': 'Cron yurishlari',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['command', '-started_at'], name='ops_cronrun_command_45a238_idx'), models.Index(fields=['status', '-started_at'], name='ops_cronrun_status_7a3a2e_idx')],
            },
        ),
    ]
