# Generated by Django 5.2.11 on 2026-02-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_additional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='about_description',
            field=models.TextField(default='Men 5+ yillik tajribaga ega Python backend arxitektiman. Django, FastAPI, PostgreSQL, Redis va Docker bilan professional darajada ishlayman. Clean Architecture va SOLID tamoyillariga amal qilgan holda yuqori samarali backend tizimlarni loyihalayman.', help_text='About section body text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, help_text='About section portrait/image', null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_title',
            field=models.CharField(default='About', help_text="About section heading (template appends 'Me' with gradient)", max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='jayson@jaysonkhan.com', help_text='Primary contact email — shown in footer and contact page', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Favicon (ICO, PNG 32×32 or 64×64)', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(default='© 2026 JaysonKhan. All rights reserved.', help_text='Footer copyright line', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_availability_badge',
            field=models.CharField(default='Available for work', help_text='Small badge text above the hero headline', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero section portrait/image', null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default='Senior Python Backend Architect specializing in Django, PostgreSQL, and Clean Architecture.', help_text='Hero sub-heading paragraph', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='I build high-performance backend systems.', help_text='Main hero headline', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Site logo — future navbar use', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(default='Senior Python Backend Architect specializing in Django, PostgreSQL, and Clean Architecture. Available for freelance and full-time work.', help_text='Google snippet description (max 160 chars)', max_length=160),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(default='Python, Django, PostgreSQL, Backend Developer, Software Architect, Portfolio', help_text='Comma-separated SEO keywords', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph preview image (1200×630 px recommended)', null=True, upload_to='seo/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='og_url',
            field=models.URLField(default='https://jaysonkhan.com', help_text='Canonical site URL for Open Graph'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='projects_page_subtitle',
            field=models.CharField(default="A detailed look at the systems and applications I've architected and implemented.", help_text='Projects page sub-heading', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='resume_button_text',
            field=models.CharField(default='Download CV', help_text='Resume download button label', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='resume_file',
            field=models.FileField(blank=True, help_text='CV / Resume PDF for download', null=True, upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_tagline',
            field=models.CharField(default='Senior Python Backend Architect & Full-stack Developer.', help_text='One-liner description — shown in footer', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(default='JaysonKhan | Portfolio', help_text='Full site name — used in <title> tag and nav logo', max_length=255),
        ),
    ]
