# Generated by Django 5.2.11 on 2026-02-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mobile_developer_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='about_description',
            field=models.TextField(default='Flutter Mobile Engineer with 2+ years of experience developing high-quality Android and iOS applications. Specialized in building scalable, maintainable, and performance-oriented mobile solutions using Clean Architecture and BLoC. Developed 15+ corporate mobile apps with complex animations, REST API integrations, and cross-platform adaptive user interfaces.', help_text='About section body text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='blog_page_subtitle',
            field=models.CharField(default='Insights on mobile development, Flutter, and building production-ready apps.', help_text='Blog list page sub-heading', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_page_subtitle',
            field=models.CharField(default='Have a mobile app idea or need a Flutter engineer? Drop me a message.', help_text='Contact page intro paragraph', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='bettaxacker@gmail.com', help_text='Primary contact email — shown in footer and contact page', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='featured_projects_subtitle',
            field=models.CharField(default="Apps I've built and shipped to production.", help_text='Featured projects section sub-heading', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='featured_projects_title',
            field=models.CharField(default='Featured Apps', help_text='Featured projects section heading', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(default='© 2026 Jahongir Kuziboev. All rights reserved.', help_text='Footer copyright line', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_primary_cta_text',
            field=models.CharField(default='View Apps', help_text='Primary CTA button text in hero', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default='Flutter Mobile Engineer specializing in building scalable, performance-oriented Android & iOS applications with Clean Architecture.', help_text='Hero sub-heading paragraph', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='I craft pixel-perfect mobile experiences.', help_text='Main hero headline', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(default='Flutter Mobile Engineer with 2+ years of experience developing high-quality Android & iOS apps. Clean Architecture, BLoC, Dart.', help_text='Google snippet description (max 160 chars)', max_length=160),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(default='Flutter, Dart, Mobile Developer, Android, iOS, BLoC, Clean Architecture, Portfolio', help_text='Comma-separated SEO keywords', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='projects_page_subtitle',
            field=models.CharField(default="A showcase of the mobile applications I've designed, developed, and shipped.", help_text='Projects page sub-heading', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='projects_page_title',
            field=models.CharField(default='App Portfolio', help_text='Projects page <h1> heading', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_author',
            field=models.CharField(default='Jahongir Kuziboev', help_text='Author name (used in blog byline and structured data)', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_tagline',
            field=models.CharField(default='Flutter Mobile Engineer — building high-quality Android & iOS apps.', help_text='One-liner description — shown in footer', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(default='Jahongir Kuziboev | Flutter Mobile Engineer', help_text='Full site name — used in <title> tag and nav logo', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='skills_section_title',
            field=models.CharField(default='Tech Stack', help_text='Skills section heading', max_length=100),
        ),
    ]
