# Generated by Django 4.2.28 on 2026-02-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sitesettings_site_title_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='apps_section_visible',
            field=models.BooleanField(default=True, help_text='Show/hide the entire Apps section (navigation link, footer link, homepage featured projects, and hero CTA). Turn OFF to temporarily hide this section across the whole site.'),
        ),
    ]
