# Generated by Django 4.2.28 on 2026-03-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_apps_visibility_and_project_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='stat_1_count',
            field=models.IntegerField(default=3, help_text='Stat 1 — numeric value for animated counter (e.g. 3)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_1_label',
            field=models.CharField(default='Years Experience', help_text='Stat 1 — label below the number', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_1_suffix',
            field=models.CharField(default='+', help_text="Stat 1 — suffix appended to count (e.g. '+', 'M+', '%')", max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_2_count',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_2_label',
            field=models.CharField(default='Apps Delivered', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_2_suffix',
            field=models.CharField(default='+', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_3_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_3_label',
            field=models.CharField(default='App Downloads', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_3_suffix',
            field=models.CharField(default='M+', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_4_count',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_4_label',
            field=models.CharField(default='Clean Architecture', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_4_suffix',
            field=models.CharField(default='%', max_length=10),
        ),
    ]
