# Generated by Django 4.2.28 on 2026-03-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
