# Generated by Django 4.2.28 on 2026-03-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pageview_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_typing_texts',
            field=models.TextField(blank=True, default='["Flutter Developer", "Mobile Engineer", "Problem Solver", "App Builder"]', help_text='JSON array of phrases for the hero typing animation. Example: ["Flutter Developer", "Mobile Engineer"]. Leave empty to disable.'),
        ),
    ]
