# Generated by Django 4.2.28 on 2026-03-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesettings_hero_typing_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='wakatime_api_key',
            field=models.CharField(blank=True, default='', help_text='WakaTime API key (from wakatime.com/settings/api-key). Used server-side only.', max_length=255),
        ),
    ]
