# Generated by Django 4.2.28 on 2026-03-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesettings_wakatime_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_notify_comments',
            field=models.BooleanField(default=True, help_text='Log new comments to admin group'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_notify_contacts',
            field=models.BooleanField(default=True, help_text='Log contact form submissions to admin group'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_notify_likes',
            field=models.BooleanField(default=True, help_text='Log likes/unlikes to admin group'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_notify_new_users',
            field=models.BooleanField(default=True, help_text='Log new user registrations to admin group'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_notify_reactions',
            field=models.BooleanField(default=True, help_text='Log reactions to admin group'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_notify_replies',
            field=models.BooleanField(default=True, help_text='Log comment replies to admin group'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_admin_group_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram group/supergroup chat ID for admin notifications.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_owner_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram user ID of the site owner. Always receives notifications.', null=True),
        ),
    ]
