# Generated by Django 4.2.28 on 2026-03-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitesettings_admin_notify_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_channel_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram channel chat ID for publishing blog posts and projects. Numeric ID (e.g. -1001234567890). Changing this allows re-sharing content to the new channel.', null=True),
        ),
    ]
