# Generated by Django 4.2.28 on 2026-03-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sitesettings_telegram_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_app_store',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 🍎 App Store button', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_bot',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 🤖 Telegram Bot button', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_comment',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 💬 Comment/reply buttons', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_google_play',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for ▶️ Google Play button', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_read_more',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 📖 Batafsil button (e.g. 5368324170671202286)', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_web',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 🌐 Web button', max_length=30),
        ),
    ]
