# Generated by Django 4.2.28 on 2026-04-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_tg_emoji_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_email',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_alert',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 🚨 Alert notifications', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_chart',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 📊 Reports/charts', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_cpu',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 🧠 CPU section', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_critical',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 🔴 Critical/down status', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_disk',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 💿 Disk section', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_money',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 💰 Tariff/pricing', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_ok',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 🟢 OK/active status', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_ram',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 💾 RAM section', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_server',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 🖥 Server/status headers', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_warn',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 🟡 Warning status', max_length=30),
        ),
    ]
