# Generated by Django 4.2.28 on 2026-04-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_tg_emoji_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_email',
        ),
    ]
