# Generated by Django 4.2.28 on 2026-04-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_server_monitor_emoji_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_extra',
            field=models.JSONField(blank=True, default=dict, help_text='Extra custom emoji IDs as JSON: {"key": "emoji_id"}. Managed via /emoji bot command.'),
        ),
    ]
