# Generated by Django 4.2.28 on 2026-04-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_tg_emoji_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_ban',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 🚫 Ban action', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_contact_msg',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 📩 Contact form log', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_education',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 🎓 TalabaOvozi source', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_greeting',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 👋 Bot greeting', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_like',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 👍 Like notification', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_lock',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 🔒 Restricted access', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_mute',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 🔇 Mute action', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_osint',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 🔍 OSINT button', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_post',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 📝 Blog post caption', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_premium',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for ⭐️ Premium badge', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_project',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 📱 Project caption', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_reply',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for ↩️ Reply notification', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_returning',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 🔄 Returning user', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_tech',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 🛠 Tech stack label', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_user',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 👤 New user icon', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tg_emoji_extra',
            field=models.JSONField(blank=True, default=dict, help_text='Extra custom emoji IDs as JSON.'),
        ),
    ]
