# Generated by Django 4.2.28 on 2026-04-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_full_emoji_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_backup_icon',
            field=models.CharField(blank=True, default='', help_text='💾 Backup', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_calendar',
            field=models.CharField(blank=True, default='', help_text='📅 Activity dates', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_channel_icon',
            field=models.CharField(blank=True, default='', help_text='📢 Channel entity', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_clock',
            field=models.CharField(blank=True, default='', help_text='🕐 Timestamp', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_config_icon',
            field=models.CharField(blank=True, default='', help_text='⚙️ Config', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_crown',
            field=models.CharField(blank=True, default='', help_text='👑 Admin count', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_downgrade',
            field=models.CharField(blank=True, default='', help_text='⬇️ Downgrade', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_error',
            field=models.CharField(blank=True, default='', help_text='❌ Error', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_group',
            field=models.CharField(blank=True, default='', help_text='👥 Group/supergroup', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_history',
            field=models.CharField(blank=True, default='', help_text='📝 Username history', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_id_badge',
            field=models.CharField(blank=True, default='', help_text='🆔 Telegram ID', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_load',
            field=models.CharField(blank=True, default='', help_text='📈 Load average', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_logs_icon',
            field=models.CharField(blank=True, default='', help_text='📋 Logs', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_nginx',
            field=models.CharField(blank=True, default='', help_text='⚡ nginx icon', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_notifications_icon',
            field=models.CharField(blank=True, default='', help_text='🔔 Notifications', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_package',
            field=models.CharField(blank=True, default='', help_text='📦 Plan package', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_pencil',
            field=models.CharField(blank=True, default='', help_text='✏️ Name history', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_phone',
            field=models.CharField(blank=True, default='', help_text='📱 Phone number', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_postgresql',
            field=models.CharField(blank=True, default='', help_text='🐘 PostgreSQL icon', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_scam_warn',
            field=models.CharField(blank=True, default='', help_text='⚠️ SCAM/warning', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_services_icon',
            field=models.CharField(blank=True, default='', help_text='🔧 Services section', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_sources',
            field=models.CharField(blank=True, default='', help_text='📡 Service sources', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_success',
            field=models.CharField(blank=True, default='', help_text='✅ Success', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_swap',
            field=models.CharField(blank=True, default='', help_text='🔄 Swap', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_trophy',
            field=models.CharField(blank=True, default='', help_text='🏆 Top processes', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_unlike',
            field=models.CharField(blank=True, default='', help_text='👎 Unlike', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_upgrade',
            field=models.CharField(blank=True, default='', help_text='⬆️ Upgrade', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_uptime',
            field=models.CharField(blank=True, default='', help_text='⏱ Uptime', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_verified',
            field=models.CharField(blank=True, default='', help_text='✅ Verified badge', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tg_emoji_ban',
            field=models.CharField(blank=True, default='', help_text='🚫 Ban', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tg_emoji_contact_msg',
            field=models.CharField(blank=True, default='', help_text='📩 Contact', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tg_emoji_education',
            field=models.CharField(blank=True, default='', help_text='🎓 TalabaOvozi', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tg_emoji_greeting',
            field=models.CharField(blank=True, default='', help_text='👋 Greeting', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tg_emoji_like',
            field=models.CharField(blank=True, default='', help_text='👍 Like', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tg_emoji_lock',
            field=models.CharField(blank=True, default='', help_text='🔒 Lock', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tg_emoji_money',
            field=models.CharField(blank=True, default='', help_text='💰 Tariff/pricing', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tg_emoji_mute',
            field=models.CharField(blank=True, default='', help_text='🔇 Mute', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tg_emoji_post',
            field=models.CharField(blank=True, default='', help_text='📝 Blog post', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tg_emoji_project',
            field=models.CharField(blank=True, default='', help_text='📱 Project', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tg_emoji_reply',
            field=models.CharField(blank=True, default='', help_text='↩️ Reply', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tg_emoji_tech',
            field=models.CharField(blank=True, default='', help_text='🛠 Tech stack', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tg_emoji_user',
            field=models.CharField(blank=True, default='', help_text='👤 User', max_length=30),
        ),
    ]
