# Generated by Django 4.2.28 on 2026-04-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_58_emoji_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_back',
            field=models.CharField(blank=True, default='', help_text='🔙 Back', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_ballot',
            field=models.CharField(blank=True, default='', help_text='🗳 Ballot box', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_blocked',
            field=models.CharField(blank=True, default='', help_text='🚫 Blocked', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_bronze',
            field=models.CharField(blank=True, default='', help_text='🥉 Bronze/3rd', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_cloud',
            field=models.CharField(blank=True, default='', help_text='☁️ Cloud', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_clover',
            field=models.CharField(blank=True, default='', help_text='🍀 Clover', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_control',
            field=models.CharField(blank=True, default='', help_text='🎛 Control', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_crown_icon',
            field=models.CharField(blank=True, default='', help_text='👑 Crown icon', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_device',
            field=models.CharField(blank=True, default='', help_text='📲 Device', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_diamond',
            field=models.CharField(blank=True, default='', help_text='💎 Diamond', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_document',
            field=models.CharField(blank=True, default='', help_text='📄 Document', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_edit',
            field=models.CharField(blank=True, default='', help_text='✏️ Edit', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_email_icon',
            field=models.CharField(blank=True, default='', help_text='📧 Email', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_eye',
            field=models.CharField(blank=True, default='', help_text='👁 Eye', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_fire',
            field=models.CharField(blank=True, default='', help_text='🔥 Fire', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_globe',
            field=models.CharField(blank=True, default='', help_text='🌐 Globe', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_gold',
            field=models.CharField(blank=True, default='', help_text='🥇 Gold/1st', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_graduation',
            field=models.CharField(blank=True, default='', help_text='🎓 Graduation', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_green_dot',
            field=models.CharField(blank=True, default='', help_text='🟢 Green dot', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_growth',
            field=models.CharField(blank=True, default='', help_text='📈 Growth', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_home',
            field=models.CharField(blank=True, default='', help_text='🏠 Home', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_key',
            field=models.CharField(blank=True, default='', help_text='🔑 Key', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_locked',
            field=models.CharField(blank=True, default='', help_text='🔒 Locked', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_mail',
            field=models.CharField(blank=True, default='', help_text='📨 Mail', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_minus',
            field=models.CharField(blank=True, default='', help_text='➖ Remove', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_mobile',
            field=models.CharField(blank=True, default='', help_text='📱 Mobile', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_moon',
            field=models.CharField(blank=True, default='', help_text='🌙 Moon', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_name_badge',
            field=models.CharField(blank=True, default='', help_text='📛 Name badge', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_numbers',
            field=models.CharField(blank=True, default='', help_text='🔢 Numbers', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_people',
            field=models.CharField(blank=True, default='', help_text='👥 People', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_person',
            field=models.CharField(blank=True, default='', help_text='👤 Person', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_phone_icon',
            field=models.CharField(blank=True, default='', help_text='📞 Phone', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_plus',
            field=models.CharField(blank=True, default='', help_text='➕ Add', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_point_down',
            field=models.CharField(blank=True, default='', help_text='👇 Point down', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_point_right',
            field=models.CharField(blank=True, default='', help_text='👉 Point right', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_pray',
            field=models.CharField(blank=True, default='', help_text='🙏 Pray', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_red_dot',
            field=models.CharField(blank=True, default='', help_text='🔴 Red dot', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_right_arrow',
            field=models.CharField(blank=True, default='', help_text='➡️ Right arrow', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_school',
            field=models.CharField(blank=True, default='', help_text='🏫 School', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_secure',
            field=models.CharField(blank=True, default='', help_text='🔐 Secure', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_settings',
            field=models.CharField(blank=True, default='', help_text='⚙️ Settings', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_shield',
            field=models.CharField(blank=True, default='', help_text='🛡 Shield', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_silver',
            field=models.CharField(blank=True, default='', help_text='🥈 Silver/2nd', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_speech',
            field=models.CharField(blank=True, default='', help_text='💬 Speech bubble', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_stats',
            field=models.CharField(blank=True, default='', help_text='📊 Stats', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_target',
            field=models.CharField(blank=True, default='', help_text='🎯 Target', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_teacher',
            field=models.CharField(blank=True, default='', help_text='👨\u200d🏫 Teacher', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_thought',
            field=models.CharField(blank=True, default='', help_text='💭 Thought bubble', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_triangle',
            field=models.CharField(blank=True, default='', help_text='🔺 Triangle', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_upload',
            field=models.CharField(blank=True, default='', help_text='📤 Upload', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_warning',
            field=models.CharField(blank=True, default='', help_text='⚠️ Warning', max_length=30),
        ),
    ]
