# Generated by Django 4.2.28 on 2026-04-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_sitesettings_tg_emoji_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_blue_square',
            field=models.CharField(blank=True, default='', help_text='🟦 Blue square', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_celebration',
            field=models.CharField(blank=True, default='', help_text='🎉 Celebration', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_lightning',
            field=models.CharField(blank=True, default='', help_text='⚡ Lightning', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_memo',
            field=models.CharField(blank=True, default='', help_text='📝 Memo/write', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_pin',
            field=models.CharField(blank=True, default='', help_text='📍 Pin/location', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_skip',
            field=models.CharField(blank=True, default='', help_text='⏭ Skip', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_undo',
            field=models.CharField(blank=True, default='', help_text='↩️ Undo', max_length=30),
        ),
    ]
