# Generated by Django 4.2.28 on 2026-04-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_sitesettings_tg_emoji_blue_square_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bing_verification',
            field=models.CharField(blank=True, default='', help_text='Bing Webmaster msvalidate.01 token', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, default='', help_text='GA4 Measurement ID, e.g. G-XXXXXXXXXX', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_site_verification',
            field=models.CharField(blank=True, default='', help_text='Google Search Console token (content= value of the meta tag)', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_metrika_id',
            field=models.CharField(blank=True, default='', help_text='Yandex Metrica counter ID (digits only)', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_verification',
            field=models.CharField(blank=True, default='', help_text='Yandex Webmaster verification token (content= value)', max_length=100),
        ),
    ]
