# Generated by Django 4.2.28 on 2026-04-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_sitesettings_bing_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tg_emoji_github',
            field=models.CharField(blank=True, default='', help_text='Custom emoji ID for 💻 GitHub button', max_length=30),
        ),
    ]
