# Generated by Django 4.2.28 on 2026-04-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_tg_emoji_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assets/%Y/%m/')),
                ('name', models.CharField(blank=True, help_text='Auto-derived from filename if blank', max_length=200)),
                ('folder', models.CharField(choices=[('hero', 'Hero'), ('apps', 'Apps'), ('team', 'Team'), ('journal', 'Journal'), ('brand', 'Brand'), ('product', 'Product'), ('misc', 'Misc')], db_index=True, default='misc', max_length=24)),
                ('alt_text', models.CharField(blank=True, help_text='Optional accessibility description', max_length=240)),
                ('format', models.CharField(blank=True, help_text='JPG, PNG, SVG, WEBP, MP4, etc.', max_length=10)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0, help_text='0 if not an image')),
                ('height', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
