# Generated by Django 4.2.28 on 2026-04-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='source',
            field=models.CharField(choices=[('upload', 'Manual upload'), ('imported', 'Imported from media'), ('linked', 'Linked from model')], default='upload', max_length=12),
        ),
        migrations.AddField(
            model_name='asset',
            name='source_path',
            field=models.CharField(blank=True, db_index=True, help_text='Original media-relative path (used to dedupe imports)', max_length=500),
        ),
        migrations.AddField(
            model_name='asset',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='How many model fields reference this file'),
        ),
        migrations.AddField(
            model_name='asset',
            name='usage_summary',
            field=models.CharField(blank=True, help_text="Comma-separated list of where this asset is used, e.g. 'Project: Halyk Pay, SiteSettings: hero_image'", max_length=500),
        ),
        migrations.AlterField(
            model_name='asset',
            name='folder',
            field=models.CharField(choices=[('hero', 'Hero'), ('apps', 'Apps'), ('team', 'Team'), ('journal', 'Journal'), ('brand', 'Brand'), ('product', 'Product'), ('experience', 'Experience'), ('misc', 'Misc')], db_index=True, default='misc', max_length=24),
        ),
    ]
