# Generated by Django 4.2.28 on 2026-04-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_asset_source_asset_source_path_asset_usage_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='availability_badge',
            field=models.CharField(blank=True, default='Now booking · Q2 2026', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='brand_tagline',
            field=models.CharField(blank=True, default='Build Studio · Est. 2022', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_availability_note',
            field=models.CharField(blank=True, default='Two engagement slots open. Tashkent, UTC+5.', max_length=240),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_availability_status',
            field=models.CharField(blank=True, default='Available · Q2 2026', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_label',
            field=models.CharField(blank=True, default='Brief / Form 7741', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_title',
            field=models.CharField(blank=True, default="Tell me what you're building.", max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button_text',
            field=models.CharField(blank=True, default='Start a conversation', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_description',
            field=models.TextField(blank=True, default='Two slots opening for Q2 2026. Best fit: ambitious mobile-first products with a 12+ week runway and a real user base in mind.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_eyebrow',
            field=models.CharField(blank=True, default='07 — Open channel', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_response_label',
            field=models.CharField(blank=True, default='Avg. response · 4–6h', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_title_em',
            field=models.CharField(blank=True, default="I'll bring the team.", max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_title_pre',
            field=models.CharField(blank=True, default='Bring the brief.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_volume',
            field=models.CharField(blank=True, default='VOL. 03 · ISSUE 01', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_eyebrow',
            field=models.CharField(blank=True, default='Personal · Build Studio · Mobile Engineering', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_location',
            field=models.CharField(blank=True, default='Tashkent · 41.2995° N', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_scroll_label',
            field=models.CharField(blank=True, default='Scroll · Begin transmission', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_section_count',
            field=models.CharField(blank=True, default='01 / 07', max_length=24),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_volume_label',
            field=models.CharField(blank=True, default='Vol. 03 · Issue 01', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifesto_eyebrow',
            field=models.CharField(blank=True, default='02 — Philosophy', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifesto_label',
            field=models.CharField(blank=True, default='03 PRINCIPLES · ON BUILDING', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifesto_principles',
            field=models.JSONField(blank=True, default=list, help_text="List of {n, title, description} dicts. n is shown as a giant numeral (e.g. '01')."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifesto_title',
            field=models.CharField(blank=True, default='Manifesto.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='metrics_description',
            field=models.TextField(blank=True, default='Numbers from live production apps over the last four years. Pulled from dashboards, not pitch decks.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='metrics_eyebrow',
            field=models.CharField(blank=True, default='03 — By the numbers', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='metrics_title',
            field=models.CharField(blank=True, default='A track record, measured.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_eyebrow',
            field=models.CharField(blank=True, default='05 — How I work', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_steps',
            field=models.JSONField(blank=True, default=list, help_text='List of {n, title, description} dicts.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_title',
            field=models.CharField(blank=True, default='Five steps, no surprises.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_hero_eyebrow',
            field=models.CharField(blank=True, default='Studio · Crew Manifest', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_intro',
            field=models.TextField(blank=True, default='A small studio of mobile engineers, designers, and operators. We combine technical execution, product thinking, and production experience to ship real apps for real users.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_section_label',
            field=models.CharField(blank=True, default='Section · 03', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_studio_label',
            field=models.CharField(blank=True, default='Studio open · Tashkent', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_values',
            field=models.JSONField(blank=True, default=list, help_text='List of {title, description} dicts.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_values_eyebrow',
            field=models.CharField(blank=True, default='Operating principles', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_values_intro',
            field=models.CharField(blank=True, default="Six values, four years together. These aren't slogans on a wall — they're the trade-offs we keep landing on.", max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_values_title',
            field=models.CharField(blank=True, default='How we think.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ticker_items',
            field=models.JSONField(blank=True, default=list, help_text="Marquee ticker items, e.g. ['Flutter mobile engineering', 'Production apps', ...]"),
        ),
    ]
