# Generated by Django 4.2.28 on 2026-04-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_sitesettings_availability_badge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_title_pre',
            field=models.CharField(blank=True, default='Bring the<br>brief.', help_text='HTML allowed. Use <br> for line breaks.', max_length=240),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='metrics_title',
            field=models.CharField(blank=True, default='A track record,<br><em style="font-weight: 300;">measured.</em>', help_text='HTML allowed. Use <br> for line breaks and <em> for italic emphasis.', max_length=240),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='process_title',
            field=models.CharField(blank=True, default='Five steps,<br><em style="font-weight: 300;">no surprises.</em>', help_text='HTML allowed. Use <br> for line breaks and <em> for italic emphasis.', max_length=240),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='team_values_title',
            field=models.CharField(blank=True, default='How we<br>think.', help_text='HTML allowed. Use <br> for line breaks.', max_length=240),
        ),
    ]
