# Generated by Django 4.2.28 on 2026-04-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_backfill_html_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_email_label',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_linkedin_label',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='experience_section_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='featured_projects_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_availability_badge',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_primary_cta_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_primary_cta_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_secondary_cta_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_secondary_cta_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_typing_texts',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='latest_blog_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='skills_section_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='wakatime_api_key',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='I craft pixel-perfect mobile experiences.', help_text='Main hero headline (HTML allowed; leave blank to use v3 default)', max_length=255),
        ),
    ]
