# Generated by Django 4.2.28 on 2026-04-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_sitesettings_contact_email_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_section_eyebrow',
            field=models.CharField(blank=True, default='About · Operator', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_section_label',
            field=models.CharField(blank=True, default='Section · 04', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_section_status',
            field=models.CharField(blank=True, default='New every fortnight', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_section_channels',
            field=models.CharField(blank=True, default='4 channels open', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_section_label',
            field=models.CharField(blank=True, default='Section · 05', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_404_description',
            field=models.TextField(blank=True, default="The page you're looking for has either been moved, archived, or never existed in the first place. Let's get you back on track."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_404_headline',
            field=models.CharField(blank=True, default='Looks like this page<br><em style="font-weight: 400;">drifted off the map.</em>', help_text='HTML allowed.', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_500_description',
            field=models.TextField(blank=True, default="An internal error occurred and the page couldn't render. The team has been notified — try again in a moment, or head back home."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_500_headline',
            field=models.CharField(blank=True, default='Something on our<br><em style="font-weight: 400;">end snapped.</em>', help_text='HTML allowed.', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_unavailable_description',
            field=models.TextField(blank=True, default='This part of the site is temporarily offline. Check back soon — it should be up again shortly.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_unavailable_headline',
            field=models.CharField(blank=True, default='This section is<br><em style="font-weight: 400;">temporarily offline.</em>', help_text='HTML allowed. Shown on /projects/ when apps_section_visible=False.', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_cta_eyebrow',
            field=models.CharField(blank=True, default='End / Transmission complete', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_cta_headline',
            field=models.CharField(blank=True, default="Got a brief?<br><em>Let's </em>open a channel.", help_text='HTML allowed. Footer ink-block CTA headline.', max_length=400),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_practice_items',
            field=models.JSONField(blank=True, default=list, help_text="List of practice/service strings, e.g. ['Web apps · Django', 'Telegram bots · Aiogram', ...]"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_section_label',
            field=models.CharField(blank=True, default='Section · 02', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_hero_headline',
            field=models.CharField(blank=True, default='Behind every<br>strong product is a<br><em>focused</em> team.', help_text='HTML allowed (<br>, <em>). Big serif headline on /team/.', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_description',
            field=models.TextField(default="Full-stack VibeCoder with 3+ years shipping production systems. I build web apps with Django, Telegram bots with Aiogram, and design systems with Tailwind — all augmented by Claude Code and a sane workflow. Background in mobile (Flutter, Android, iOS), but the studio's center of gravity has moved to web + bots + AI.", help_text='About section body text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='blog_page_subtitle',
            field=models.CharField(default='Notes on AI-augmented development, full-stack delivery, and shipping production systems that actually run.', help_text='Blog list page sub-heading', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_page_subtitle',
            field=models.CharField(default="Building a web app, Telegram bot, or AI-augmented system? Let's ship it together.", help_text='Contact page intro paragraph', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_description',
            field=models.TextField(blank=True, default='Two slots opening for Q2 2026. Best fit: ambitious web apps, Telegram bot products, or AI-augmented systems with a 12+ week runway and a real user base in mind.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_eyebrow',
            field=models.CharField(blank=True, default='Personal · Build Studio · VibeCoder', max_length=160),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default='VibeCoder shipping production-grade web applications, Telegram bots, and AI-augmented systems. Built fast with Claude Code, built to last with Django.', help_text='Hero sub-heading paragraph', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='I ship production web apps and Telegram bots.', help_text='Main hero headline (HTML allowed; leave blank to use v3 default)', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(default='Jaysonkhan — VibeCoder shipping production web apps & Telegram bots via AI-augmented development. Build Studio · Tashkent.', help_text='Google snippet description (max 160 chars)', max_length=160),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(default='VibeCoder, Django, Python, Telegram bots, AI development, Claude Code, full stack, build studio, Tashkent', help_text='Comma-separated SEO keywords', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_tagline',
            field=models.CharField(default='VibeCoder — shipping production web apps & Telegram bots via AI-augmented development.', help_text='One-liner description — shown in footer', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(default='Jaysonkhan | VibeCoder · Build Studio', help_text='Full site name — used in the page title tag and nav logo', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='team_intro',
            field=models.TextField(blank=True, default='A small studio of full-stack builders, designers, and operators. We ship production web apps, Telegram bots, and AI-augmented systems — using whatever tool fits the problem.'),
        ),
    ]
