# Generated by Django 4.2.28 on 2026-04-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_finalize_vibecoder_rebrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='alt_text_en',
            field=models.CharField(blank=True, help_text='Optional accessibility description', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='alt_text_ru',
            field=models.CharField(blank=True, help_text='Optional accessibility description', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='alt_text_uz',
            field=models.CharField(blank=True, help_text='Optional accessibility description', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='alt_text_xo',
            field=models.CharField(blank=True, help_text='Optional accessibility description', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='name_en',
            field=models.CharField(blank=True, help_text='Auto-derived from filename if blank', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='name_ru',
            field=models.CharField(blank=True, help_text='Auto-derived from filename if blank', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='name_uz',
            field=models.CharField(blank=True, help_text='Auto-derived from filename if blank', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='name_xo',
            field=models.CharField(blank=True, help_text='Auto-derived from filename if blank', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_description_en',
            field=models.TextField(default="Full-stack VibeCoder with 3+ years shipping production systems. I build web apps with Django, Telegram bots with Aiogram, and design systems with Tailwind — all augmented by Claude Code and a sane workflow. Background in mobile (Flutter, Android, iOS), but the studio's center of gravity has moved to web + bots + AI.", help_text='About section body text', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_description_ru',
            field=models.TextField(default="Full-stack VibeCoder with 3+ years shipping production systems. I build web apps with Django, Telegram bots with Aiogram, and design systems with Tailwind — all augmented by Claude Code and a sane workflow. Background in mobile (Flutter, Android, iOS), but the studio's center of gravity has moved to web + bots + AI.", help_text='About section body text', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_description_uz',
            field=models.TextField(default="Full-stack VibeCoder with 3+ years shipping production systems. I build web apps with Django, Telegram bots with Aiogram, and design systems with Tailwind — all augmented by Claude Code and a sane workflow. Background in mobile (Flutter, Android, iOS), but the studio's center of gravity has moved to web + bots + AI.", help_text='About section body text', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_description_xo',
            field=models.TextField(default="Full-stack VibeCoder with 3+ years shipping production systems. I build web apps with Django, Telegram bots with Aiogram, and design systems with Tailwind — all augmented by Claude Code and a sane workflow. Background in mobile (Flutter, Android, iOS), but the studio's center of gravity has moved to web + bots + AI.", help_text='About section body text', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_section_eyebrow_en',
            field=models.CharField(blank=True, default='About · Operator', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_section_eyebrow_ru',
            field=models.CharField(blank=True, default='About · Operator', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_section_eyebrow_uz',
            field=models.CharField(blank=True, default='About · Operator', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_section_eyebrow_xo',
            field=models.CharField(blank=True, default='About · Operator', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title_en',
            field=models.CharField(default='About', help_text="About section heading (template appends 'Me' with gradient)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title_ru',
            field=models.CharField(default='About', help_text="About section heading (template appends 'Me' with gradient)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title_uz',
            field=models.CharField(default='About', help_text="About section heading (template appends 'Me' with gradient)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title_xo',
            field=models.CharField(default='About', help_text="About section heading (template appends 'Me' with gradient)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='availability_badge_en',
            field=models.CharField(blank=True, default='Now booking · Q2 2026', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='availability_badge_ru',
            field=models.CharField(blank=True, default='Now booking · Q2 2026', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='availability_badge_uz',
            field=models.CharField(blank=True, default='Now booking · Q2 2026', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='availability_badge_xo',
            field=models.CharField(blank=True, default='Now booking · Q2 2026', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_page_subtitle_en',
            field=models.CharField(default='Notes on AI-augmented development, full-stack delivery, and shipping production systems that actually run.', help_text='Blog list page sub-heading', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_page_subtitle_ru',
            field=models.CharField(default='Notes on AI-augmented development, full-stack delivery, and shipping production systems that actually run.', help_text='Blog list page sub-heading', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_page_subtitle_uz',
            field=models.CharField(default='Notes on AI-augmented development, full-stack delivery, and shipping production systems that actually run.', help_text='Blog list page sub-heading', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_page_subtitle_xo',
            field=models.CharField(default='Notes on AI-augmented development, full-stack delivery, and shipping production systems that actually run.', help_text='Blog list page sub-heading', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_page_title_en',
            field=models.CharField(default='The Blog', help_text='Blog list page <h1> heading', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_page_title_ru',
            field=models.CharField(default='The Blog', help_text='Blog list page <h1> heading', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_page_title_uz',
            field=models.CharField(default='The Blog', help_text='Blog list page <h1> heading', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_page_title_xo',
            field=models.CharField(default='The Blog', help_text='Blog list page <h1> heading', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='brand_tagline_en',
            field=models.CharField(blank=True, default='Build Studio · Est. 2022', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='brand_tagline_ru',
            field=models.CharField(blank=True, default='Build Studio · Est. 2022', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='brand_tagline_uz',
            field=models.CharField(blank=True, default='Build Studio · Est. 2022', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='brand_tagline_xo',
            field=models.CharField(blank=True, default='Build Studio · Est. 2022', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_availability_note_en',
            field=models.CharField(blank=True, default='Two engagement slots open. Tashkent, UTC+5.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_availability_note_ru',
            field=models.CharField(blank=True, default='Two engagement slots open. Tashkent, UTC+5.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_availability_note_uz',
            field=models.CharField(blank=True, default='Two engagement slots open. Tashkent, UTC+5.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_availability_note_xo',
            field=models.CharField(blank=True, default='Two engagement slots open. Tashkent, UTC+5.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_availability_status_en',
            field=models.CharField(blank=True, default='Available · Q2 2026', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_availability_status_ru',
            field=models.CharField(blank=True, default='Available · Q2 2026', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_availability_status_uz',
            field=models.CharField(blank=True, default='Available · Q2 2026', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_availability_status_xo',
            field=models.CharField(blank=True, default='Available · Q2 2026', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_label_en',
            field=models.CharField(blank=True, default='Brief / Form 7741', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_label_ru',
            field=models.CharField(blank=True, default='Brief / Form 7741', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_label_uz',
            field=models.CharField(blank=True, default='Brief / Form 7741', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_label_xo',
            field=models.CharField(blank=True, default='Brief / Form 7741', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_title_en',
            field=models.CharField(blank=True, default="Tell me what you're building.", max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_title_ru',
            field=models.CharField(blank=True, default="Tell me what you're building.", max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_title_uz',
            field=models.CharField(blank=True, default="Tell me what you're building.", max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_title_xo',
            field=models.CharField(blank=True, default="Tell me what you're building.", max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_page_subtitle_en',
            field=models.CharField(default="Building a web app, Telegram bot, or AI-augmented system? Let's ship it together.", help_text='Contact page intro paragraph', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_page_subtitle_ru',
            field=models.CharField(default="Building a web app, Telegram bot, or AI-augmented system? Let's ship it together.", help_text='Contact page intro paragraph', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_page_subtitle_uz',
            field=models.CharField(default="Building a web app, Telegram bot, or AI-augmented system? Let's ship it together.", help_text='Contact page intro paragraph', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_page_subtitle_xo',
            field=models.CharField(default="Building a web app, Telegram bot, or AI-augmented system? Let's ship it together.", help_text='Contact page intro paragraph', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_page_title_en',
            field=models.CharField(default='Get in touch', help_text='Contact page <h1> heading', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_page_title_ru',
            field=models.CharField(default='Get in touch', help_text='Contact page <h1> heading', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_page_title_uz',
            field=models.CharField(default='Get in touch', help_text='Contact page <h1> heading', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_page_title_xo',
            field=models.CharField(default='Get in touch', help_text='Contact page <h1> heading', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button_text_en',
            field=models.CharField(blank=True, default='Start a conversation', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button_text_ru',
            field=models.CharField(blank=True, default='Start a conversation', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button_text_uz',
            field=models.CharField(blank=True, default='Start a conversation', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button_text_xo',
            field=models.CharField(blank=True, default='Start a conversation', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_description_en',
            field=models.TextField(blank=True, default='Two slots opening for Q2 2026. Best fit: ambitious web apps, Telegram bot products, or AI-augmented systems with a 12+ week runway and a real user base in mind.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_description_ru',
            field=models.TextField(blank=True, default='Two slots opening for Q2 2026. Best fit: ambitious web apps, Telegram bot products, or AI-augmented systems with a 12+ week runway and a real user base in mind.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_description_uz',
            field=models.TextField(blank=True, default='Two slots opening for Q2 2026. Best fit: ambitious web apps, Telegram bot products, or AI-augmented systems with a 12+ week runway and a real user base in mind.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_description_xo',
            field=models.TextField(blank=True, default='Two slots opening for Q2 2026. Best fit: ambitious web apps, Telegram bot products, or AI-augmented systems with a 12+ week runway and a real user base in mind.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_eyebrow_en',
            field=models.CharField(blank=True, default='07 — Open channel', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_eyebrow_ru',
            field=models.CharField(blank=True, default='07 — Open channel', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_eyebrow_uz',
            field=models.CharField(blank=True, default='07 — Open channel', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_eyebrow_xo',
            field=models.CharField(blank=True, default='07 — Open channel', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_response_label_en',
            field=models.CharField(blank=True, default='Avg. response · 4–6h', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_response_label_ru',
            field=models.CharField(blank=True, default='Avg. response · 4–6h', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_response_label_uz',
            field=models.CharField(blank=True, default='Avg. response · 4–6h', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_response_label_xo',
            field=models.CharField(blank=True, default='Avg. response · 4–6h', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_title_em_en',
            field=models.CharField(blank=True, default="I'll bring the team.", max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_title_em_ru',
            field=models.CharField(blank=True, default="I'll bring the team.", max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_title_em_uz',
            field=models.CharField(blank=True, default="I'll bring the team.", max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_title_em_xo',
            field=models.CharField(blank=True, default="I'll bring the team.", max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_title_pre_en',
            field=models.CharField(blank=True, default='Bring the<br>brief.', help_text='HTML allowed. Use <br> for line breaks.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_title_pre_ru',
            field=models.CharField(blank=True, default='Bring the<br>brief.', help_text='HTML allowed. Use <br> for line breaks.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_title_pre_uz',
            field=models.CharField(blank=True, default='Bring the<br>brief.', help_text='HTML allowed. Use <br> for line breaks.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_title_pre_xo',
            field=models.CharField(blank=True, default='Bring the<br>brief.', help_text='HTML allowed. Use <br> for line breaks.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_404_description_en',
            field=models.TextField(blank=True, default="The page you're looking for has either been moved, archived, or never existed in the first place. Let's get you back on track.", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_404_description_ru',
            field=models.TextField(blank=True, default="The page you're looking for has either been moved, archived, or never existed in the first place. Let's get you back on track.", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_404_description_uz',
            field=models.TextField(blank=True, default="The page you're looking for has either been moved, archived, or never existed in the first place. Let's get you back on track.", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_404_description_xo',
            field=models.TextField(blank=True, default="The page you're looking for has either been moved, archived, or never existed in the first place. Let's get you back on track.", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_404_headline_en',
            field=models.CharField(blank=True, default='Looks like this page<br><em style="font-weight: 400;">drifted off the map.</em>', help_text='HTML allowed.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_404_headline_ru',
            field=models.CharField(blank=True, default='Looks like this page<br><em style="font-weight: 400;">drifted off the map.</em>', help_text='HTML allowed.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_404_headline_uz',
            field=models.CharField(blank=True, default='Looks like this page<br><em style="font-weight: 400;">drifted off the map.</em>', help_text='HTML allowed.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_404_headline_xo',
            field=models.CharField(blank=True, default='Looks like this page<br><em style="font-weight: 400;">drifted off the map.</em>', help_text='HTML allowed.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_500_description_en',
            field=models.TextField(blank=True, default="An internal error occurred and the page couldn't render. The team has been notified — try again in a moment, or head back home.", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_500_description_ru',
            field=models.TextField(blank=True, default="An internal error occurred and the page couldn't render. The team has been notified — try again in a moment, or head back home.", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_500_description_uz',
            field=models.TextField(blank=True, default="An internal error occurred and the page couldn't render. The team has been notified — try again in a moment, or head back home.", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_500_description_xo',
            field=models.TextField(blank=True, default="An internal error occurred and the page couldn't render. The team has been notified — try again in a moment, or head back home.", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_500_headline_en',
            field=models.CharField(blank=True, default='Something on our<br><em style="font-weight: 400;">end snapped.</em>', help_text='HTML allowed.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_500_headline_ru',
            field=models.CharField(blank=True, default='Something on our<br><em style="font-weight: 400;">end snapped.</em>', help_text='HTML allowed.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_500_headline_uz',
            field=models.CharField(blank=True, default='Something on our<br><em style="font-weight: 400;">end snapped.</em>', help_text='HTML allowed.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_500_headline_xo',
            field=models.CharField(blank=True, default='Something on our<br><em style="font-weight: 400;">end snapped.</em>', help_text='HTML allowed.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_unavailable_description_en',
            field=models.TextField(blank=True, default='This part of the site is temporarily offline. Check back soon — it should be up again shortly.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_unavailable_description_ru',
            field=models.TextField(blank=True, default='This part of the site is temporarily offline. Check back soon — it should be up again shortly.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_unavailable_description_uz',
            field=models.TextField(blank=True, default='This part of the site is temporarily offline. Check back soon — it should be up again shortly.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_unavailable_description_xo',
            field=models.TextField(blank=True, default='This part of the site is temporarily offline. Check back soon — it should be up again shortly.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_unavailable_headline_en',
            field=models.CharField(blank=True, default='This section is<br><em style="font-weight: 400;">temporarily offline.</em>', help_text='HTML allowed. Shown on /projects/ when apps_section_visible=False.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_unavailable_headline_ru',
            field=models.CharField(blank=True, default='This section is<br><em style="font-weight: 400;">temporarily offline.</em>', help_text='HTML allowed. Shown on /projects/ when apps_section_visible=False.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_unavailable_headline_uz',
            field=models.CharField(blank=True, default='This section is<br><em style="font-weight: 400;">temporarily offline.</em>', help_text='HTML allowed. Shown on /projects/ when apps_section_visible=False.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_unavailable_headline_xo',
            field=models.CharField(blank=True, default='This section is<br><em style="font-weight: 400;">temporarily offline.</em>', help_text='HTML allowed. Shown on /projects/ when apps_section_visible=False.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_projects_title_en',
            field=models.CharField(default='Featured Apps', help_text='Featured projects section heading', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_projects_title_ru',
            field=models.CharField(default='Featured Apps', help_text='Featured projects section heading', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_projects_title_uz',
            field=models.CharField(default='Featured Apps', help_text='Featured projects section heading', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_projects_title_xo',
            field=models.CharField(default='Featured Apps', help_text='Featured projects section heading', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_cta_eyebrow_en',
            field=models.CharField(blank=True, default='End / Transmission complete', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_cta_eyebrow_ru',
            field=models.CharField(blank=True, default='End / Transmission complete', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_cta_eyebrow_uz',
            field=models.CharField(blank=True, default='End / Transmission complete', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_cta_eyebrow_xo',
            field=models.CharField(blank=True, default='End / Transmission complete', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_cta_headline_en',
            field=models.CharField(blank=True, default="Got a brief?<br><em>Let's </em>open a channel.", help_text='HTML allowed. Footer ink-block CTA headline.', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_cta_headline_ru',
            field=models.CharField(blank=True, default="Got a brief?<br><em>Let's </em>open a channel.", help_text='HTML allowed. Footer ink-block CTA headline.', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_cta_headline_uz',
            field=models.CharField(blank=True, default="Got a brief?<br><em>Let's </em>open a channel.", help_text='HTML allowed. Footer ink-block CTA headline.', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_cta_headline_xo',
            field=models.CharField(blank=True, default="Got a brief?<br><em>Let's </em>open a channel.", help_text='HTML allowed. Footer ink-block CTA headline.', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_description_en',
            field=models.TextField(blank=True, default='', help_text='Footer description text (leave blank to use site_tagline)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_description_ru',
            field=models.TextField(blank=True, default='', help_text='Footer description text (leave blank to use site_tagline)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_description_uz',
            field=models.TextField(blank=True, default='', help_text='Footer description text (leave blank to use site_tagline)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_description_xo',
            field=models.TextField(blank=True, default='', help_text='Footer description text (leave blank to use site_tagline)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_practice_items_en',
            field=models.JSONField(blank=True, default=list, help_text="List of practice/service strings, e.g. ['Web apps · Django', 'Telegram bots · Aiogram', ...]", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_practice_items_ru',
            field=models.JSONField(blank=True, default=list, help_text="List of practice/service strings, e.g. ['Web apps · Django', 'Telegram bots · Aiogram', ...]", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_practice_items_uz',
            field=models.JSONField(blank=True, default=list, help_text="List of practice/service strings, e.g. ['Web apps · Django', 'Telegram bots · Aiogram', ...]", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_practice_items_xo',
            field=models.JSONField(blank=True, default=list, help_text="List of practice/service strings, e.g. ['Web apps · Django', 'Telegram bots · Aiogram', ...]", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_en',
            field=models.CharField(default='© 2026 Jahongir Kuziboev. All rights reserved.', help_text='Footer copyright line', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_ru',
            field=models.CharField(default='© 2026 Jahongir Kuziboev. All rights reserved.', help_text='Footer copyright line', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_uz',
            field=models.CharField(default='© 2026 Jahongir Kuziboev. All rights reserved.', help_text='Footer copyright line', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_xo',
            field=models.CharField(default='© 2026 Jahongir Kuziboev. All rights reserved.', help_text='Footer copyright line', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_eyebrow_en',
            field=models.CharField(blank=True, default='Personal · Build Studio · VibeCoder', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_eyebrow_ru',
            field=models.CharField(blank=True, default='Personal · Build Studio · VibeCoder', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_eyebrow_uz',
            field=models.CharField(blank=True, default='Personal · Build Studio · VibeCoder', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_eyebrow_xo',
            field=models.CharField(blank=True, default='Personal · Build Studio · VibeCoder', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_en',
            field=models.TextField(default='VibeCoder shipping production-grade web applications, Telegram bots, and AI-augmented systems. Built fast with Claude Code, built to last with Django.', help_text='Hero sub-heading paragraph', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_ru',
            field=models.TextField(default='VibeCoder shipping production-grade web applications, Telegram bots, and AI-augmented systems. Built fast with Claude Code, built to last with Django.', help_text='Hero sub-heading paragraph', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_uz',
            field=models.TextField(default='VibeCoder shipping production-grade web applications, Telegram bots, and AI-augmented systems. Built fast with Claude Code, built to last with Django.', help_text='Hero sub-heading paragraph', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_xo',
            field=models.TextField(default='VibeCoder shipping production-grade web applications, Telegram bots, and AI-augmented systems. Built fast with Claude Code, built to last with Django.', help_text='Hero sub-heading paragraph', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_en',
            field=models.CharField(default='I ship production web apps and Telegram bots.', help_text='Main hero headline (HTML allowed; leave blank to use v3 default)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_ru',
            field=models.CharField(default='I ship production web apps and Telegram bots.', help_text='Main hero headline (HTML allowed; leave blank to use v3 default)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_uz',
            field=models.CharField(default='I ship production web apps and Telegram bots.', help_text='Main hero headline (HTML allowed; leave blank to use v3 default)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_xo',
            field=models.CharField(default='I ship production web apps and Telegram bots.', help_text='Main hero headline (HTML allowed; leave blank to use v3 default)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifesto_eyebrow_en',
            field=models.CharField(blank=True, default='02 — Philosophy', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifesto_eyebrow_ru',
            field=models.CharField(blank=True, default='02 — Philosophy', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifesto_eyebrow_uz',
            field=models.CharField(blank=True, default='02 — Philosophy', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifesto_eyebrow_xo',
            field=models.CharField(blank=True, default='02 — Philosophy', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifesto_label_en',
            field=models.CharField(blank=True, default='03 PRINCIPLES · ON BUILDING', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifesto_label_ru',
            field=models.CharField(blank=True, default='03 PRINCIPLES · ON BUILDING', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifesto_label_uz',
            field=models.CharField(blank=True, default='03 PRINCIPLES · ON BUILDING', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifesto_label_xo',
            field=models.CharField(blank=True, default='03 PRINCIPLES · ON BUILDING', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifesto_principles_en',
            field=models.JSONField(blank=True, default=list, help_text="List of {n, title, description} dicts. n is shown as a giant numeral (e.g. '01').", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifesto_principles_ru',
            field=models.JSONField(blank=True, default=list, help_text="List of {n, title, description} dicts. n is shown as a giant numeral (e.g. '01').", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifesto_principles_uz',
            field=models.JSONField(blank=True, default=list, help_text="List of {n, title, description} dicts. n is shown as a giant numeral (e.g. '01').", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifesto_principles_xo',
            field=models.JSONField(blank=True, default=list, help_text="List of {n, title, description} dicts. n is shown as a giant numeral (e.g. '01').", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifesto_title_en',
            field=models.CharField(blank=True, default='Manifesto.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifesto_title_ru',
            field=models.CharField(blank=True, default='Manifesto.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifesto_title_uz',
            field=models.CharField(blank=True, default='Manifesto.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifesto_title_xo',
            field=models.CharField(blank=True, default='Manifesto.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_en',
            field=models.TextField(default='Jaysonkhan — VibeCoder shipping production web apps & Telegram bots via AI-augmented development. Build Studio · Tashkent.', help_text='Google snippet description (max 160 chars)', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_ru',
            field=models.TextField(default='Jaysonkhan — VibeCoder shipping production web apps & Telegram bots via AI-augmented development. Build Studio · Tashkent.', help_text='Google snippet description (max 160 chars)', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_uz',
            field=models.TextField(default='Jaysonkhan — VibeCoder shipping production web apps & Telegram bots via AI-augmented development. Build Studio · Tashkent.', help_text='Google snippet description (max 160 chars)', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_xo',
            field=models.TextField(default='Jaysonkhan — VibeCoder shipping production web apps & Telegram bots via AI-augmented development. Build Studio · Tashkent.', help_text='Google snippet description (max 160 chars)', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords_en',
            field=models.CharField(default='VibeCoder, Django, Python, Telegram bots, AI development, Claude Code, full stack, build studio, Tashkent', help_text='Comma-separated SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords_ru',
            field=models.CharField(default='VibeCoder, Django, Python, Telegram bots, AI development, Claude Code, full stack, build studio, Tashkent', help_text='Comma-separated SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords_uz',
            field=models.CharField(default='VibeCoder, Django, Python, Telegram bots, AI development, Claude Code, full stack, build studio, Tashkent', help_text='Comma-separated SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords_xo',
            field=models.CharField(default='VibeCoder, Django, Python, Telegram bots, AI development, Claude Code, full stack, build studio, Tashkent', help_text='Comma-separated SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='metrics_description_en',
            field=models.TextField(blank=True, default='Numbers from live production apps over the last four years. Pulled from dashboards, not pitch decks.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='metrics_description_ru',
            field=models.TextField(blank=True, default='Numbers from live production apps over the last four years. Pulled from dashboards, not pitch decks.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='metrics_description_uz',
            field=models.TextField(blank=True, default='Numbers from live production apps over the last four years. Pulled from dashboards, not pitch decks.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='metrics_description_xo',
            field=models.TextField(blank=True, default='Numbers from live production apps over the last four years. Pulled from dashboards, not pitch decks.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='metrics_eyebrow_en',
            field=models.CharField(blank=True, default='03 — By the numbers', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='metrics_eyebrow_ru',
            field=models.CharField(blank=True, default='03 — By the numbers', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='metrics_eyebrow_uz',
            field=models.CharField(blank=True, default='03 — By the numbers', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='metrics_eyebrow_xo',
            field=models.CharField(blank=True, default='03 — By the numbers', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='metrics_title_en',
            field=models.CharField(blank=True, default='A track record,<br><em style="font-weight: 300;">measured.</em>', help_text='HTML allowed. Use <br> for line breaks and <em> for italic emphasis.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='metrics_title_ru',
            field=models.CharField(blank=True, default='A track record,<br><em style="font-weight: 300;">measured.</em>', help_text='HTML allowed. Use <br> for line breaks and <em> for italic emphasis.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='metrics_title_uz',
            field=models.CharField(blank=True, default='A track record,<br><em style="font-weight: 300;">measured.</em>', help_text='HTML allowed. Use <br> for line breaks and <em> for italic emphasis.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='metrics_title_xo',
            field=models.CharField(blank=True, default='A track record,<br><em style="font-weight: 300;">measured.</em>', help_text='HTML allowed. Use <br> for line breaks and <em> for italic emphasis.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_cta_text_en',
            field=models.CharField(default='Hire Me', help_text='Navigation CTA button label', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_cta_text_ru',
            field=models.CharField(default='Hire Me', help_text='Navigation CTA button label', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_cta_text_uz',
            field=models.CharField(default='Hire Me', help_text='Navigation CTA button label', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_cta_text_xo',
            field=models.CharField(default='Hire Me', help_text='Navigation CTA button label', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_eyebrow_en',
            field=models.CharField(blank=True, default='05 — How I work', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_eyebrow_ru',
            field=models.CharField(blank=True, default='05 — How I work', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_eyebrow_uz',
            field=models.CharField(blank=True, default='05 — How I work', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_eyebrow_xo',
            field=models.CharField(blank=True, default='05 — How I work', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_steps_en',
            field=models.JSONField(blank=True, default=list, help_text='List of {n, title, description} dicts.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_steps_ru',
            field=models.JSONField(blank=True, default=list, help_text='List of {n, title, description} dicts.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_steps_uz',
            field=models.JSONField(blank=True, default=list, help_text='List of {n, title, description} dicts.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_steps_xo',
            field=models.JSONField(blank=True, default=list, help_text='List of {n, title, description} dicts.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_title_en',
            field=models.CharField(blank=True, default='Five steps,<br><em style="font-weight: 300;">no surprises.</em>', help_text='HTML allowed. Use <br> for line breaks and <em> for italic emphasis.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_title_ru',
            field=models.CharField(blank=True, default='Five steps,<br><em style="font-weight: 300;">no surprises.</em>', help_text='HTML allowed. Use <br> for line breaks and <em> for italic emphasis.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_title_uz',
            field=models.CharField(blank=True, default='Five steps,<br><em style="font-weight: 300;">no surprises.</em>', help_text='HTML allowed. Use <br> for line breaks and <em> for italic emphasis.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_title_xo',
            field=models.CharField(blank=True, default='Five steps,<br><em style="font-weight: 300;">no surprises.</em>', help_text='HTML allowed. Use <br> for line breaks and <em> for italic emphasis.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_page_subtitle_en',
            field=models.CharField(default="A showcase of the mobile applications I've designed, developed, and shipped.", help_text='Projects page sub-heading', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_page_subtitle_ru',
            field=models.CharField(default="A showcase of the mobile applications I've designed, developed, and shipped.", help_text='Projects page sub-heading', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_page_subtitle_uz',
            field=models.CharField(default="A showcase of the mobile applications I've designed, developed, and shipped.", help_text='Projects page sub-heading', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_page_subtitle_xo',
            field=models.CharField(default="A showcase of the mobile applications I've designed, developed, and shipped.", help_text='Projects page sub-heading', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_page_title_en',
            field=models.CharField(default='App Portfolio', help_text='Projects page <h1> heading', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_page_title_ru',
            field=models.CharField(default='App Portfolio', help_text='Projects page <h1> heading', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_page_title_uz',
            field=models.CharField(default='App Portfolio', help_text='Projects page <h1> heading', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_page_title_xo',
            field=models.CharField(default='App Portfolio', help_text='Projects page <h1> heading', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='resume_button_text_en',
            field=models.CharField(default='Download CV', help_text='Resume download button label', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='resume_button_text_ru',
            field=models.CharField(default='Download CV', help_text='Resume download button label', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='resume_button_text_uz',
            field=models.CharField(default='Download CV', help_text='Resume download button label', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='resume_button_text_xo',
            field=models.CharField(default='Download CV', help_text='Resume download button label', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_tagline_en',
            field=models.CharField(default='VibeCoder — shipping production web apps & Telegram bots via AI-augmented development.', help_text='One-liner description — shown in footer', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_tagline_ru',
            field=models.CharField(default='VibeCoder — shipping production web apps & Telegram bots via AI-augmented development.', help_text='One-liner description — shown in footer', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_tagline_uz',
            field=models.CharField(default='VibeCoder — shipping production web apps & Telegram bots via AI-augmented development.', help_text='One-liner description — shown in footer', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_tagline_xo',
            field=models.CharField(default='VibeCoder — shipping production web apps & Telegram bots via AI-augmented development.', help_text='One-liner description — shown in footer', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_title_en',
            field=models.CharField(default='Jaysonkhan | VibeCoder · Build Studio', help_text='Full site name — used in the page title tag and nav logo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_title_ru',
            field=models.CharField(default='Jaysonkhan | VibeCoder · Build Studio', help_text='Full site name — used in the page title tag and nav logo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_title_uz',
            field=models.CharField(default='Jaysonkhan | VibeCoder · Build Studio', help_text='Full site name — used in the page title tag and nav logo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_title_xo',
            field=models.CharField(default='Jaysonkhan | VibeCoder · Build Studio', help_text='Full site name — used in the page title tag and nav logo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_1_label_en',
            field=models.CharField(default='Years Experience', help_text='Stat 1 — label below the number', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_1_label_ru',
            field=models.CharField(default='Years Experience', help_text='Stat 1 — label below the number', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_1_label_uz',
            field=models.CharField(default='Years Experience', help_text='Stat 1 — label below the number', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_1_label_xo',
            field=models.CharField(default='Years Experience', help_text='Stat 1 — label below the number', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_2_label_en',
            field=models.CharField(default='Apps Delivered', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_2_label_ru',
            field=models.CharField(default='Apps Delivered', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_2_label_uz',
            field=models.CharField(default='Apps Delivered', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_2_label_xo',
            field=models.CharField(default='Apps Delivered', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_3_label_en',
            field=models.CharField(default='App Downloads', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_3_label_ru',
            field=models.CharField(default='App Downloads', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_3_label_uz',
            field=models.CharField(default='App Downloads', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_3_label_xo',
            field=models.CharField(default='App Downloads', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_4_label_en',
            field=models.CharField(default='Clean Architecture', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_4_label_ru',
            field=models.CharField(default='Clean Architecture', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_4_label_uz',
            field=models.CharField(default='Clean Architecture', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_4_label_xo',
            field=models.CharField(default='Clean Architecture', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_hero_eyebrow_en',
            field=models.CharField(blank=True, default='Studio · Crew Manifest', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_hero_eyebrow_ru',
            field=models.CharField(blank=True, default='Studio · Crew Manifest', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_hero_eyebrow_uz',
            field=models.CharField(blank=True, default='Studio · Crew Manifest', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_hero_eyebrow_xo',
            field=models.CharField(blank=True, default='Studio · Crew Manifest', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_hero_headline_en',
            field=models.CharField(blank=True, default='Behind every<br>strong product is a<br><em>focused</em> team.', help_text='HTML allowed (<br>, <em>). Big serif headline on /team/.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_hero_headline_ru',
            field=models.CharField(blank=True, default='Behind every<br>strong product is a<br><em>focused</em> team.', help_text='HTML allowed (<br>, <em>). Big serif headline on /team/.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_hero_headline_uz',
            field=models.CharField(blank=True, default='Behind every<br>strong product is a<br><em>focused</em> team.', help_text='HTML allowed (<br>, <em>). Big serif headline on /team/.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_hero_headline_xo',
            field=models.CharField(blank=True, default='Behind every<br>strong product is a<br><em>focused</em> team.', help_text='HTML allowed (<br>, <em>). Big serif headline on /team/.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_intro_en',
            field=models.TextField(blank=True, default='A small studio of full-stack builders, designers, and operators. We ship production web apps, Telegram bots, and AI-augmented systems — using whatever tool fits the problem.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_intro_ru',
            field=models.TextField(blank=True, default='A small studio of full-stack builders, designers, and operators. We ship production web apps, Telegram bots, and AI-augmented systems — using whatever tool fits the problem.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_intro_uz',
            field=models.TextField(blank=True, default='A small studio of full-stack builders, designers, and operators. We ship production web apps, Telegram bots, and AI-augmented systems — using whatever tool fits the problem.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_intro_xo',
            field=models.TextField(blank=True, default='A small studio of full-stack builders, designers, and operators. We ship production web apps, Telegram bots, and AI-augmented systems — using whatever tool fits the problem.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_values_en',
            field=models.JSONField(blank=True, default=list, help_text='List of {title, description} dicts.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_values_eyebrow_en',
            field=models.CharField(blank=True, default='Operating principles', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_values_eyebrow_ru',
            field=models.CharField(blank=True, default='Operating principles', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_values_eyebrow_uz',
            field=models.CharField(blank=True, default='Operating principles', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_values_eyebrow_xo',
            field=models.CharField(blank=True, default='Operating principles', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_values_intro_en',
            field=models.CharField(blank=True, default="Six values, four years together. These aren't slogans on a wall — they're the trade-offs we keep landing on.", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_values_intro_ru',
            field=models.CharField(blank=True, default="Six values, four years together. These aren't slogans on a wall — they're the trade-offs we keep landing on.", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_values_intro_uz',
            field=models.CharField(blank=True, default="Six values, four years together. These aren't slogans on a wall — they're the trade-offs we keep landing on.", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_values_intro_xo',
            field=models.CharField(blank=True, default="Six values, four years together. These aren't slogans on a wall — they're the trade-offs we keep landing on.", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_values_ru',
            field=models.JSONField(blank=True, default=list, help_text='List of {title, description} dicts.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_values_title_en',
            field=models.CharField(blank=True, default='How we<br>think.', help_text='HTML allowed. Use <br> for line breaks.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_values_title_ru',
            field=models.CharField(blank=True, default='How we<br>think.', help_text='HTML allowed. Use <br> for line breaks.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_values_title_uz',
            field=models.CharField(blank=True, default='How we<br>think.', help_text='HTML allowed. Use <br> for line breaks.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_values_title_xo',
            field=models.CharField(blank=True, default='How we<br>think.', help_text='HTML allowed. Use <br> for line breaks.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_values_uz',
            field=models.JSONField(blank=True, default=list, help_text='List of {title, description} dicts.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_values_xo',
            field=models.JSONField(blank=True, default=list, help_text='List of {title, description} dicts.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ticker_items_en',
            field=models.JSONField(blank=True, default=list, help_text="Marquee ticker items, e.g. ['Flutter mobile engineering', 'Production apps', ...]", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ticker_items_ru',
            field=models.JSONField(blank=True, default=list, help_text="Marquee ticker items, e.g. ['Flutter mobile engineering', 'Production apps', ...]", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ticker_items_uz',
            field=models.JSONField(blank=True, default=list, help_text="Marquee ticker items, e.g. ['Flutter mobile engineering', 'Production apps', ...]", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ticker_items_xo',
            field=models.JSONField(blank=True, default=list, help_text="Marquee ticker items, e.g. ['Flutter mobile engineering', 'Production apps', ...]", null=True),
        ),
    ]
