# Generated by Django 4.2.28 on 2026-04-26 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_translate_site_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettingsBranding',
            fields=[
            ],
            options={
                'verbose_name': 'Brending',
                'verbose_name_plural': 'Brending sozlamalari',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteSettingsContact',
            fields=[
            ],
            options={
                'verbose_name': 'Aloqa & Ijtimoiy',
                'verbose_name_plural': 'Aloqa & Ijtimoiy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteSettingsEditorial',
            fields=[
            ],
            options={
                'verbose_name': 'Editorial v3',
                'verbose_name_plural': 'Editorial v3 mazmuni',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteSettingsEmoji',
            fields=[
            ],
            options={
                'verbose_name': 'Emoji sozlamalari',
                'verbose_name_plural': 'Emoji sozlamalari',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteSettingsHomepage',
            fields=[
            ],
            options={
                'verbose_name': 'Bosh sahifa',
                'verbose_name_plural': 'Bosh sahifa mazmuni',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteSettingsNavigation',
            fields=[
            ],
            options={
                'verbose_name': 'Navigatsiya & Footer',
                'verbose_name_plural': 'Navigatsiya & Footer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteSettingsSEO',
            fields=[
            ],
            options={
                'verbose_name': 'SEO & Analitika',
                'verbose_name_plural': 'SEO & Analitika sozlamalari',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteSettingsTelegram',
            fields=[
            ],
            options={
                'verbose_name': 'Telegram Bot',
                'verbose_name_plural': 'Telegram Bot sozlamalari',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
    ]
