# Generated by Django 4.2.28 on 2026-06-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_humanize_cta_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='landing_path',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pageview',
            name='referrer',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pageview',
            name='source',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Classified origin: google / chatgpt / facebook / instagram / telegram / direct / …', max_length=32),
        ),
        migrations.AddField(
            model_name='pageview',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='pageview',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pageview',
            name='utm_content',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pageview',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pageview',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pageview',
            name='utm_term',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
