# Generated by Django 4.2.28 on 2026-06-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_pageview_landing_path_pageview_referrer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_em',
            field=models.CharField(blank=True, default='', help_text='Accent word(s) rendered as the italic terracotta line with the turquoise underline (XIVA INK hero signature). Leave blank to hide.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_em_en',
            field=models.CharField(blank=True, default='', help_text='Accent word(s) rendered as the italic terracotta line with the turquoise underline (XIVA INK hero signature). Leave blank to hide.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_em_ru',
            field=models.CharField(blank=True, default='', help_text='Accent word(s) rendered as the italic terracotta line with the turquoise underline (XIVA INK hero signature). Leave blank to hide.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_em_uz',
            field=models.CharField(blank=True, default='', help_text='Accent word(s) rendered as the italic terracotta line with the turquoise underline (XIVA INK hero signature). Leave blank to hide.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_em_xo',
            field=models.CharField(blank=True, default='', help_text='Accent word(s) rendered as the italic terracotta line with the turquoise underline (XIVA INK hero signature). Leave blank to hide.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='wakatime_stats',
            field=models.JSONField(blank=True, default=dict, help_text='Weekly coding stats for the homepage WakaTime widget — {total, days: [{d, h, pct, peak}], langs: [{name, pct}]}. Filled by `manage.py fetch_wakatime` (WAKATIME_API_KEY env); empty dict hides the widget.'),
        ),
    ]
