# Generated by Django 4.2.28 on 2026-06-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_sitesettings_hero_title_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='faq_items',
            field=models.JSONField(blank=True, default=list, help_text='List of {q, a} dicts. Rendered as a visible FAQ + FAQPage structured data.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_items_en',
            field=models.JSONField(blank=True, default=list, help_text='List of {q, a} dicts. Rendered as a visible FAQ + FAQPage structured data.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_items_ru',
            field=models.JSONField(blank=True, default=list, help_text='List of {q, a} dicts. Rendered as a visible FAQ + FAQPage structured data.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_items_uz',
            field=models.JSONField(blank=True, default=list, help_text='List of {q, a} dicts. Rendered as a visible FAQ + FAQPage structured data.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_items_xo',
            field=models.JSONField(blank=True, default=list, help_text='List of {q, a} dicts. Rendered as a visible FAQ + FAQPage structured data.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_title',
            field=models.CharField(blank=True, default='Frequently asked questions', help_text='Heading for the homepage FAQ section.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_title_en',
            field=models.CharField(blank=True, default='Frequently asked questions', help_text='Heading for the homepage FAQ section.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_title_ru',
            field=models.CharField(blank=True, default='Frequently asked questions', help_text='Heading for the homepage FAQ section.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_title_uz',
            field=models.CharField(blank=True, default='Frequently asked questions', help_text='Heading for the homepage FAQ section.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_title_xo',
            field=models.CharField(blank=True, default='Frequently asked questions', help_text='Heading for the homepage FAQ section.', max_length=200, null=True),
        ),
    ]
