# Generated by Django 4.2.28 on 2026-07-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_sitesettings_faq_items_sitesettings_faq_items_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_image_anime',
            field=models.ImageField(blank=True, help_text="About'da KO'RINADIGAN anime/ghibli cover — bosilganda asosiy rasm ochiladi (bo'sh = asosiy rasm)", null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, help_text="About section portrait/image (lightbox'da ochiladigan asosiy rasm)", null=True, upload_to='about/'),
        ),
    ]
