# Generated by Django 4.2.28 on 2026-03-15 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('osint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsintAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('branch_fetch', 'Branch Fetch'), ('search', 'Search'), ('resolve', 'Resolve'), ('text_search', 'Text Search'), ('channel_messages', 'Channel Messages'), ('channel_search', 'Channel Search'), ('photo_proxy', 'Photo Proxy'), ('balance_check', 'Balance Check')], db_index=True, max_length=30)),
                ('endpoint_type', models.CharField(blank=True, default='', max_length=30)),
                ('target_id', models.CharField(blank=True, default='', max_length=255)),
                ('cached', models.BooleanField(default=False, help_text='Whether result was served from cache')),
                ('api_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='API call duration in milliseconds', null=True)),
                ('error', models.TextField(blank=True, default='', help_text='Error message if the operation failed')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OSINT Audit Log',
                'verbose_name_plural': 'OSINT Audit Logs',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['-performed_at'], name='osint_osint_perform_55afaa_idx'), models.Index(fields=['action', '-performed_at'], name='osint_osint_action_08bd2c_idx')],
            },
        ),
    ]
