# Generated by Django 4.2.28 on 2026-03-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint', '0002_osintauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsintPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('use_osint', 'Full OSINT access (search, profiles, intelligence)')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
