# Generated by Django 4.2.28 on 2026-02-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_mobile_developer_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
    ]
