# Generated by Django 4.2.28 on 2026-02-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_is_bot_web_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Show this project in the Apps section. Uncheck to hide it from the project list and detail page even when the Apps section is enabled.'),
        ),
    ]
