# Generated by Django 4.2.28 on 2026-02-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_project_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_rich',
            field=models.TextField(blank=True, help_text='Rich text description (HTML)', null=True),
        ),
    ]
