# Generated by Django 4.2.28 on 2026-02-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_project_description_rich'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.DeleteModel(
            name='ProjectScreenshot',
        ),
    ]
