# Generated by Django 4.2.28 on 2026-02-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_project_description_delete_projectscreenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('architecture', 'Architecture'), ('backend', 'Backend & Networking'), ('database', 'Databases'), ('security', 'Security'), ('performance', 'Performance'), ('media', 'Media & Streaming'), ('devops', 'DevOps & Tools'), ('uiux', 'UI/UX')], default='mobile', help_text='Skill category for grouped display', max_length=20),
        ),
    ]
