# Generated by Django 4.2.28 on 2026-03-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='platform',
        ),
        migrations.AlterField(
            model_name='project',
            name='is_bot',
            field=models.BooleanField(default=False, help_text='Show in the Telegram Bot section'),
        ),
        migrations.AlterField(
            model_name='project',
            name='web_page_url',
            field=models.URLField(blank=True, help_text='Web page / live URL'),
        ),
    ]
