# Generated by Django 4.2.28 on 2026-03-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_project_platform_alter_project_is_bot_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_visible', 'order', '-created_at'], name='proj_visible_order'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_featured', 'is_visible'], name='proj_featured'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_bot', 'is_visible'], name='proj_bot'),
        ),
    ]
