# Generated by Django 4.2.28 on 2026-03-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_project_proj_visible_order_project_proj_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='case_study_challenge',
            field=models.TextField(blank=True, default='', help_text='Case Study — Challenge/Problem (leave empty to hide)'),
        ),
        migrations.AddField(
            model_name='project',
            name='case_study_results',
            field=models.TextField(blank=True, default='', help_text='Case Study — Results/Outcomes'),
        ),
        migrations.AddField(
            model_name='project',
            name='case_study_solution',
            field=models.TextField(blank=True, default='', help_text='Case Study — Solution approach'),
        ),
    ]
