# Generated by Django 4.2.28 on 2026-04-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_project_case_study_challenge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(help_text='e.g. Founder · Lead Mobile', max_length=160)),
                ('bio', models.TextField(help_text='2-4 sentences about the member')),
                ('photo', models.ImageField(blank=True, help_text='Square portrait (recommended 800x800)', null=True, upload_to='team/')),
                ('quote', models.CharField(blank=True, help_text='Optional one-liner shown in the dossier modal', max_length=240)),
                ('skills', models.CharField(blank=True, help_text="Comma-separated, e.g. 'Flutter, Bloc, Architecture, iOS, Android'", max_length=400)),
                ('years_experience', models.PositiveIntegerField(default=0, help_text="Total years of experience (shown as '4y')")),
                ('telegram_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Lower = displayed first')),
            ],
            options={
                'verbose_name': 'Team member',
                'verbose_name_plural': 'Team members',
                'ordering': ['order', 'id'],
            },
        ),
    ]
