# Generated by Django 4.2.28 on 2026-04-26 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='show_in_hero',
        ),
    ]
