# Generated by Django 4.2.28 on 2026-04-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_remove_skill_icon_remove_skill_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_xo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_xo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='location_en',
            field=models.CharField(blank=True, help_text='e.g. Tashkent, Uzbekistan', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='location_ru',
            field=models.CharField(blank=True, help_text='e.g. Tashkent, Uzbekistan', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='location_uz',
            field=models.CharField(blank=True, help_text='e.g. Tashkent, Uzbekistan', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='location_xo',
            field=models.CharField(blank=True, help_text='e.g. Tashkent, Uzbekistan', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_xo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='case_study_challenge_en',
            field=models.TextField(blank=True, default='', help_text='Case Study — Challenge/Problem (leave empty to hide)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='case_study_challenge_ru',
            field=models.TextField(blank=True, default='', help_text='Case Study — Challenge/Problem (leave empty to hide)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='case_study_challenge_uz',
            field=models.TextField(blank=True, default='', help_text='Case Study — Challenge/Problem (leave empty to hide)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='case_study_challenge_xo',
            field=models.TextField(blank=True, default='', help_text='Case Study — Challenge/Problem (leave empty to hide)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='case_study_results_en',
            field=models.TextField(blank=True, default='', help_text='Case Study — Results/Outcomes', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='case_study_results_ru',
            field=models.TextField(blank=True, default='', help_text='Case Study — Results/Outcomes', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='case_study_results_uz',
            field=models.TextField(blank=True, default='', help_text='Case Study — Results/Outcomes', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='case_study_results_xo',
            field=models.TextField(blank=True, default='', help_text='Case Study — Results/Outcomes', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='case_study_solution_en',
            field=models.TextField(blank=True, default='', help_text='Case Study — Solution approach', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='case_study_solution_ru',
            field=models.TextField(blank=True, default='', help_text='Case Study — Solution approach', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='case_study_solution_uz',
            field=models.TextField(blank=True, default='', help_text='Case Study — Solution approach', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='case_study_solution_xo',
            field=models.TextField(blank=True, default='', help_text='Case Study — Solution approach', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_rich_en',
            field=models.TextField(blank=True, help_text='Rich text description (HTML)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_rich_ru',
            field=models.TextField(blank=True, help_text='Rich text description (HTML)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_rich_uz',
            field=models.TextField(blank=True, help_text='Rich text description (HTML)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_rich_xo',
            field=models.TextField(blank=True, help_text='Rich text description (HTML)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_en',
            field=models.CharField(blank=True, help_text='One-liner for project cards (falls back to truncated description)', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_ru',
            field=models.CharField(blank=True, help_text='One-liner for project cards (falls back to truncated description)', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_uz',
            field=models.CharField(blank=True, help_text='One-liner for project cards (falls back to truncated description)', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_xo',
            field=models.CharField(blank=True, help_text='One-liner for project cards (falls back to truncated description)', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_xo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_xo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_en',
            field=models.TextField(help_text='2-4 sentences about the member', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_ru',
            field=models.TextField(help_text='2-4 sentences about the member', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_uz',
            field=models.TextField(help_text='2-4 sentences about the member', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_xo',
            field=models.TextField(help_text='2-4 sentences about the member', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_uz',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_xo',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='quote_en',
            field=models.CharField(blank=True, help_text='Optional one-liner shown in the dossier modal', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='quote_ru',
            field=models.CharField(blank=True, help_text='Optional one-liner shown in the dossier modal', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='quote_uz',
            field=models.CharField(blank=True, help_text='Optional one-liner shown in the dossier modal', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='quote_xo',
            field=models.CharField(blank=True, help_text='Optional one-liner shown in the dossier modal', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_en',
            field=models.CharField(help_text='e.g. Founder · Lead Mobile', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_ru',
            field=models.CharField(help_text='e.g. Founder · Lead Mobile', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_uz',
            field=models.CharField(help_text='e.g. Founder · Lead Mobile', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_xo',
            field=models.CharField(help_text='e.g. Founder · Lead Mobile', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='skills_en',
            field=models.CharField(blank=True, help_text="Comma-separated, e.g. 'Flutter, Bloc, Architecture, iOS, Android'", max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='skills_ru',
            field=models.CharField(blank=True, help_text="Comma-separated, e.g. 'Flutter, Bloc, Architecture, iOS, Android'", max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='skills_uz',
            field=models.CharField(blank=True, help_text="Comma-separated, e.g. 'Flutter, Bloc, Architecture, iOS, Android'", max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='skills_xo',
            field=models.CharField(blank=True, help_text="Comma-separated, e.g. 'Flutter, Bloc, Architecture, iOS, Android'", max_length=400, null=True),
        ),
    ]
