# Generated by Django 4.2.28 on 2026-06-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_normalize_xo_and_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stats',
            field=models.JSONField(blank=True, default=list, help_text='Key metrics for cards/case-study hero — list of {"v": "500k+", "l": "downloads"} objects (max 3 shown)'),
        ),
    ]
