# Generated by Django 4.2.28 on 2026-07-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_project_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('hint', models.CharField(help_text="Hover'da chiqadigan qisqa izoh (4 tilda)", max_length=200)),
                ('hint_xo', models.CharField(help_text="Hover'da chiqadigan qisqa izoh (4 tilda)", max_length=200, null=True)),
                ('hint_uz', models.CharField(help_text="Hover'da chiqadigan qisqa izoh (4 tilda)", max_length=200, null=True)),
                ('hint_ru', models.CharField(help_text="Hover'da chiqadigan qisqa izoh (4 tilda)", max_length=200, null=True)),
                ('hint_en', models.CharField(help_text="Hover'da chiqadigan qisqa izoh (4 tilda)", max_length=200, null=True)),
                ('width', models.PositiveIntegerField(default=0, editable=False)),
                ('height', models.PositiveIntegerField(default=0, editable=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Lower = displayed first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery image',
                'verbose_name_plural': 'Gallery images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
