# Generated by Django 4.2.28 on 2026-07-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='cover',
            field=models.ImageField(blank=True, help_text="Devorda ko'rinadigan anime/ghibli cover (bo'sh = original ko'rinadi)", null=True, upload_to='gallery/covers/'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='cover_height',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='cover_width',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text="Asosiy (original) rasm — lightbox'da ochiladi", upload_to='gallery/'),
        ),
    ]
