# Generated by Django 4.2.28 on 2026-07-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_galleryimage_cover_galleryimage_cover_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='photo_real',
            field=models.ImageField(blank=True, help_text="Realistik portret — modal'da anime rasm bosilganda ochiladi (bo'sh = faqat anime ko'rinadi)", null=True, upload_to='team/real/'),
        ),
    ]
