# Generated by Django 4.2.28 on 2026-02-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_comment_image_comment_parent_commentreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_reviewed',
            field=models.BooleanField(default=False, help_text='Marked as True when an admin has seen/approved this comment manually.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='If False, the comment is hidden from users.'),
        ),
    ]
