# Generated by Django 4.2.28 on 2026-03-13 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_comment_is_reviewed_alter_comment_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replies_enabled', models.BooleanField(default=True, help_text='Receive notification when someone replies to your comment')),
                ('reactions_enabled', models.BooleanField(default=True, help_text='Receive notification when someone reacts to your comment')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_pref', to='interactions.telegramprofile')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='AdminLogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(help_text='Telegram message_id in the admin group', unique=True)),
                ('event_type', models.CharField(choices=[('comment', 'New Comment'), ('reply', 'Reply'), ('reaction', 'Reaction'), ('like', 'Like'), ('contact', 'Contact Form'), ('new_user', 'New User')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_log_messages', to='interactions.telegramprofile')),
            ],
            options={
                'verbose_name': 'Admin Log Message',
                'verbose_name_plural': 'Admin Log Messages',
            },
        ),
        migrations.CreateModel(
            name='UserBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_type', models.CharField(choices=[('ban', 'Permanent Ban'), ('mute', 'Temporary Mute')], max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null = permanent ban. Set for temporary mutes.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='interactions.telegramprofile')),
            ],
            options={
                'verbose_name': 'User Ban',
                'verbose_name_plural': 'User Bans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', 'is_active'], name='ban_profile_active')],
            },
        ),
    ]
