# Generated by Django 4.2.28 on 2026-03-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_notificationpreference_adminlogmessage_userban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlogmessage',
            name='message_id',
            field=models.BigIntegerField(help_text='Telegram message_id in the admin group', unique=True),
        ),
    ]
