# Generated by Django 4.2.28 on 2026-03-15 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_data_migration'),
        ('interactions', '0005_alter_adminlogmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlogmessage',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_log_messages', to='telegram.telegramentity'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='telegram.telegramentity'),
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramentity'),
        ),
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='telegram.telegramentity'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_pref', to='telegram.telegramentity'),
        ),
        migrations.AlterField(
            model_name='userban',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='telegram.telegramentity'),
        ),
        migrations.DeleteModel(
            name='TelegramProfile',
        ),
    ]
