# Generated by Django 4.2.28 on 2026-03-16 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('interactions', '0006_alter_adminlogmessage_profile_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('channel_id', models.BigIntegerField(help_text='Telegram channel chat_id this was shared to')),
                ('telegram_message_id', models.BigIntegerField(blank=True, help_text='Message ID returned by Telegram after publishing', null=True)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_shares', to='contenttypes.contenttype')),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shared_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='cs_ct_oid')],
                'unique_together': {('content_type', 'object_id', 'channel_id')},
            },
        ),
    ]
