# Generated by Django 4.2.28 on 2026-07-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0008_alter_comment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotChatPref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('language', models.CharField(default='uz', help_text="Bot reply language for this chat ('uz' or 'ru')", max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot Chat Preference',
                'verbose_name_plural': 'Bot Chat Preferences',
            },
        ),
    ]
