# Generated by Django 4.2.28 on 2026-03-15 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('entity_type', models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('group', 'Group'), ('supergroup', 'Supergroup'), ('channel', 'Channel')], default='user', max_length=20)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('username', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', help_text='Group/channel title', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('bio', models.TextField(blank=True, default='')),
                ('photo_file', models.CharField(blank=True, default='', help_text='Relative path under MEDIA_ROOT (e.g. osint/photos/123.jpg)', max_length=255)),
                ('photo_fetched_at', models.DateTimeField(blank=True, help_text='Qachon Telegram dan yuklangan', null=True)),
                ('has_photo', models.BooleanField(default=None, help_text='None=unknown, True=has photo, False=no photo (negative cache)', null=True)),
                ('photo_url', models.URLField(blank=True, default='', help_text='Avatar URL from Telegram Login Widget')),
                ('auth_date', models.IntegerField(blank=True, help_text='Unix timestamp from Telegram Login Widget', null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_scam', models.BooleanField(default=False)),
                ('is_fake', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Entity',
                'verbose_name_plural': 'Telegram Entities',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_string', models.TextField(help_text='Telethon StringSession.save() natijasi')),
                ('account_id', models.BigIntegerField(blank=True, help_text='Telegram account ID (me.id)', null=True)),
                ('account_name', models.CharField(blank=True, default='', help_text='Account display name (first_name + username)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Session',
                'verbose_name_plural': 'Telegram Sessions',
            },
        ),
        migrations.CreateModel(
            name='EntitySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('site', 'Website (jaysonkhan.com)'), ('osint', 'OSINT'), ('rektor', 'Rektor Bot'), ('ovoz', 'Ovoz Bot')], max_length=20)),
                ('role', models.CharField(blank=True, default='', help_text='e.g. member, admin, subscriber, searched', max_length=50)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Service-specific metadata')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='telegram.telegramentity')),
            ],
            options={
                'verbose_name': 'Entity Source',
                'verbose_name_plural': 'Entity Sources',
                'ordering': ['-updated_at'],
                'unique_together': {('entity', 'service')},
            },
        ),
    ]
