# Generated by Django 4.2.28 on 2026-03-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramentity',
            name='photo_url',
            field=models.URLField(blank=True, default='', help_text='Public avatar URL — photo service yuklaganda avtomatik yangilanadi'),
        ),
    ]
