# Generated by Django 4.2.28 on 2026-03-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_alter_telegramentity_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsession',
            name='api_hash',
            field=models.CharField(blank=True, default='', help_text='Telegram API Hash', max_length=64),
        ),
        migrations.AddField(
            model_name='telegramsession',
            name='api_id',
            field=models.IntegerField(blank=True, help_text='Telegram API ID (my.telegram.org/apps dan oling)', null=True),
        ),
        migrations.AlterField(
            model_name='telegramsession',
            name='session_string',
            field=models.TextField(blank=True, default='', help_text='Telethon StringSession.save() natijasi'),
        ),
    ]
