# Generated by Django 4.2.28 on 2026-06-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_remove_telegramsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitysource',
            name='service',
            field=models.CharField(choices=[('site', 'Website (jaysonkhan.com)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='telegramentity',
            name='photo_file',
            field=models.CharField(blank=True, default='', help_text='Relative path under MEDIA_ROOT (e.g. telegram/photos/123.jpg)', max_length=255),
        ),
    ]
